-- Create Cages Table
create table kandang (
  id bigint generated by default as identity primary key,
  nama_kandang text not null,
  kapasitas int not null,
  jumlah_puyuh int not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Purchases Table
create table pembelian (
  id bigint generated by default as identity primary key,
  nama_barang text not null,
  kategori text not null check (kategori in ('pakan', 'obat', 'perlengkapan')),
  jumlah int not null,
  satuan text not null,
  harga_total numeric not null,
  tanggal date not null default current_date,
  kandang_id bigint references kandang(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Feeding Table
create table pemberian_pakan (
  id bigint generated by default as identity primary key,
  kandang_id bigint references kandang(id) not null,
  jumlah_pakan numeric not null, -- dalam kg
  jenis_pakan text not null,
  tanggal timestamp with time zone default timezone('utc'::text, now()) not null,
  catatan text
);

-- Create Admins Table (Profiles)
create table admins (
  id uuid not null primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text default 'admin',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Row Level Security)
alter table kandang enable row level security;
alter table pembelian enable row level security;
alter table pemberian_pakan enable row level security;
alter table admins enable row level security;

-- Create Policies
-- Allow authenticated users (admins) to do everything
create policy "Enable all access for authenticated users" on kandang for all using (auth.role() = 'authenticated');
create policy "Enable all access for authenticated users" on pembelian for all using (auth.role() = 'authenticated');
create policy "Enable all access for authenticated users" on pemberian_pakan for all using (auth.role() = 'authenticated');

-- Admin policies
create policy "Enable read access for authenticated admins" on admins for select using (auth.role() = 'authenticated');
create policy "Enable update access for users based on email" on admins for update using (auth.uid() = id);

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.admins (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
